POST http://localhost:8080/candidate
content-type: application/json

{
    "name": "Luiz Eduardo",
    "username": "leduardo",
    "email": "l.eduardo8316@gmail.com",
    "password": "12345678910",
    "description": "EU SOU UM CANDIDATO MUITO MANEIRO E LEGAL!!"
}
###
GET http://localhost:8080/candidate

###

POST http://localhost:8080/auth/candidate
content-type: application/json

{
    "username": "leduardo",
    "password": "12345678910"
}
###

###
POST http://localhost:8080/company
content-type: application/json

{
    "name": "Compass UOL",
    "username": "compassuol",
    "email": "contact@compass.com",
    "password": "senhaextraforte",
    "website": "www.compass.com",
    "description": "Uma empresa muito maneira, para se trabalhar!"
}
###

# @name authCompany
POST http://localhost:8080/auth/company
content-type: application/json

{
    "username": "compassuol",
    "password": "senhaextraforte"
}
###

POST http://localhost:8080/job
content-type: application/json
Authorization: Bearer {{authCompany.request.body.access_token}}

{
    "description": "Vaga para um dev junior",
    "benefits": "não tem",
    "level": "tem que ter doutourado",
    "compensation": 1200
}
###