POST http://localhost:8080/candidate
content-type: application/json

{
    "name": "Luiz Eduardo",
    "username": "leduardo",
    "email": "l.eduardo8316@gmail.com",
    "password": "12345678910",
    "description": "EU SOU UM CANDIDATO MUITO MANEIRO E LEGAL!!"
}
###

POST http://localhost:8080/auth/candidate
content-type: application/json

{
    "username": "leduardo",
    "password": "12345678910"
}
###

GET http://localhost:8080/candidate
Authorization: Bearer .eyJpc3MiOiJ2YWNhbmN5TWFuYWdlbWVudCIsImV4cCI6MTcwMDU4OTk1MSwicm9sZXMiOlsiY2FuZGlkYXRlIl0sInN1YiI6IjRjMjFkNDk3LTA5ZjMtNDk1NS1iMWRmLTA5MDgwMjM1ZDY5NSIsImdyYW50X3R5cGUiOiJjYW5kaWRhdGUifQ.l_GbPHLXQdr-mHORU776l4dE04wka3G81Yd-0_CyUJ0

###


###
POST http://localhost:8080/company
content-type: application/json

{
    "name": "Compass UOL",
    "username": "compassuol",
    "email": "contact@compass.com",
    "password": "senhaextraforte",
    "website": "www.compass.com",
    "description": "Uma empresa muito maneira, para se trabalhar!"
}
###

# @name authCompany
POST http://localhost:8080/auth/company
content-type: application/json

{
    "username": "compassuol",
    "password": "senhaextraforte"
}
###

POST http://localhost:8080/job
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ2YWNhbmN5TWFuYWdlbWVudCIsImV4cCI6MTcwMDU4ODQzMywic3ViIjoiNDNlZmFhMjAtMTdjMC00ZWQ5LWIwNWMtNDhhMjZiNzBhMTQ3In0.uMeov6l2gHlgEXpQ3_IEYRJ-j112l7LBeuAj2tDLfLg

{
    "description": "Vaga para um dev junior",
    "benefits": "não tem",
    "level": "tem que ter doutourado",
    "compensation": 1200
}
###