version: "3.8"

services:
  postgres:
    container_name: "vacancy_managment_postgres"
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=vacancy_managment
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
