version: "3.8"

services:
  postgres:
    container_name: "vacancy_managment_postgres"
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=vacancy_managment
    volumes:
      - pgdata:/data/postgres

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - vacancy-managment-network
    ports:
      - "9090:9090"

networks:
  vacancy-managment-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
  prometheus_data:
    driver: local
