global:
  scrape_interval: 6s

scrape_configs:
  - job_name: "api-vacancy-manegement"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["127.0.0.1:8080"]
        labels:
          application: "api-vacancy-manegement"